# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cx/桌面/webserver_new/my-WebServer-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cx/桌面/webserver_new/my-WebServer-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cx/桌面/webserver_new/my-WebServer-main/CMakeFiles /home/cx/桌面/webserver_new/my-WebServer-main/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cx/桌面/webserver_new/my-WebServer-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_WebServer

# Build rule for target.
my_WebServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_WebServer
.PHONY : my_WebServer

# fast build rule for target.
my_WebServer/fast:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/build
.PHONY : my_WebServer/fast

codes/buffer.o: codes/buffer.cpp.o

.PHONY : codes/buffer.o

# target to build an object file
codes/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/buffer.cpp.o
.PHONY : codes/buffer.cpp.o

codes/buffer.i: codes/buffer.cpp.i

.PHONY : codes/buffer.i

# target to preprocess a source file
codes/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/buffer.cpp.i
.PHONY : codes/buffer.cpp.i

codes/buffer.s: codes/buffer.cpp.s

.PHONY : codes/buffer.s

# target to generate assembly for a file
codes/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/buffer.cpp.s
.PHONY : codes/buffer.cpp.s

codes/epoller.o: codes/epoller.cpp.o

.PHONY : codes/epoller.o

# target to build an object file
codes/epoller.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/epoller.cpp.o
.PHONY : codes/epoller.cpp.o

codes/epoller.i: codes/epoller.cpp.i

.PHONY : codes/epoller.i

# target to preprocess a source file
codes/epoller.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/epoller.cpp.i
.PHONY : codes/epoller.cpp.i

codes/epoller.s: codes/epoller.cpp.s

.PHONY : codes/epoller.s

# target to generate assembly for a file
codes/epoller.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/epoller.cpp.s
.PHONY : codes/epoller.cpp.s

codes/heaptimer.o: codes/heaptimer.cpp.o

.PHONY : codes/heaptimer.o

# target to build an object file
codes/heaptimer.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/heaptimer.cpp.o
.PHONY : codes/heaptimer.cpp.o

codes/heaptimer.i: codes/heaptimer.cpp.i

.PHONY : codes/heaptimer.i

# target to preprocess a source file
codes/heaptimer.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/heaptimer.cpp.i
.PHONY : codes/heaptimer.cpp.i

codes/heaptimer.s: codes/heaptimer.cpp.s

.PHONY : codes/heaptimer.s

# target to generate assembly for a file
codes/heaptimer.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/heaptimer.cpp.s
.PHONY : codes/heaptimer.cpp.s

codes/httpconn.o: codes/httpconn.cpp.o

.PHONY : codes/httpconn.o

# target to build an object file
codes/httpconn.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpconn.cpp.o
.PHONY : codes/httpconn.cpp.o

codes/httpconn.i: codes/httpconn.cpp.i

.PHONY : codes/httpconn.i

# target to preprocess a source file
codes/httpconn.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpconn.cpp.i
.PHONY : codes/httpconn.cpp.i

codes/httpconn.s: codes/httpconn.cpp.s

.PHONY : codes/httpconn.s

# target to generate assembly for a file
codes/httpconn.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpconn.cpp.s
.PHONY : codes/httpconn.cpp.s

codes/httprequest.o: codes/httprequest.cpp.o

.PHONY : codes/httprequest.o

# target to build an object file
codes/httprequest.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httprequest.cpp.o
.PHONY : codes/httprequest.cpp.o

codes/httprequest.i: codes/httprequest.cpp.i

.PHONY : codes/httprequest.i

# target to preprocess a source file
codes/httprequest.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httprequest.cpp.i
.PHONY : codes/httprequest.cpp.i

codes/httprequest.s: codes/httprequest.cpp.s

.PHONY : codes/httprequest.s

# target to generate assembly for a file
codes/httprequest.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httprequest.cpp.s
.PHONY : codes/httprequest.cpp.s

codes/httpresponse.o: codes/httpresponse.cpp.o

.PHONY : codes/httpresponse.o

# target to build an object file
codes/httpresponse.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpresponse.cpp.o
.PHONY : codes/httpresponse.cpp.o

codes/httpresponse.i: codes/httpresponse.cpp.i

.PHONY : codes/httpresponse.i

# target to preprocess a source file
codes/httpresponse.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpresponse.cpp.i
.PHONY : codes/httpresponse.cpp.i

codes/httpresponse.s: codes/httpresponse.cpp.s

.PHONY : codes/httpresponse.s

# target to generate assembly for a file
codes/httpresponse.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/httpresponse.cpp.s
.PHONY : codes/httpresponse.cpp.s

codes/log.o: codes/log.cpp.o

.PHONY : codes/log.o

# target to build an object file
codes/log.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/log.cpp.o
.PHONY : codes/log.cpp.o

codes/log.i: codes/log.cpp.i

.PHONY : codes/log.i

# target to preprocess a source file
codes/log.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/log.cpp.i
.PHONY : codes/log.cpp.i

codes/log.s: codes/log.cpp.s

.PHONY : codes/log.s

# target to generate assembly for a file
codes/log.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/log.cpp.s
.PHONY : codes/log.cpp.s

codes/sqlconnpoll.o: codes/sqlconnpoll.cpp.o

.PHONY : codes/sqlconnpoll.o

# target to build an object file
codes/sqlconnpoll.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/sqlconnpoll.cpp.o
.PHONY : codes/sqlconnpoll.cpp.o

codes/sqlconnpoll.i: codes/sqlconnpoll.cpp.i

.PHONY : codes/sqlconnpoll.i

# target to preprocess a source file
codes/sqlconnpoll.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/sqlconnpoll.cpp.i
.PHONY : codes/sqlconnpoll.cpp.i

codes/sqlconnpoll.s: codes/sqlconnpoll.cpp.s

.PHONY : codes/sqlconnpoll.s

# target to generate assembly for a file
codes/sqlconnpoll.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/sqlconnpoll.cpp.s
.PHONY : codes/sqlconnpoll.cpp.s

codes/webserver.o: codes/webserver.cpp.o

.PHONY : codes/webserver.o

# target to build an object file
codes/webserver.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/webserver.cpp.o
.PHONY : codes/webserver.cpp.o

codes/webserver.i: codes/webserver.cpp.i

.PHONY : codes/webserver.i

# target to preprocess a source file
codes/webserver.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/webserver.cpp.i
.PHONY : codes/webserver.cpp.i

codes/webserver.s: codes/webserver.cpp.s

.PHONY : codes/webserver.s

# target to generate assembly for a file
codes/webserver.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/codes/webserver.cpp.s
.PHONY : codes/webserver.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/my_WebServer.dir/build.make CMakeFiles/my_WebServer.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... my_WebServer"
	@echo "... codes/buffer.o"
	@echo "... codes/buffer.i"
	@echo "... codes/buffer.s"
	@echo "... codes/epoller.o"
	@echo "... codes/epoller.i"
	@echo "... codes/epoller.s"
	@echo "... codes/heaptimer.o"
	@echo "... codes/heaptimer.i"
	@echo "... codes/heaptimer.s"
	@echo "... codes/httpconn.o"
	@echo "... codes/httpconn.i"
	@echo "... codes/httpconn.s"
	@echo "... codes/httprequest.o"
	@echo "... codes/httprequest.i"
	@echo "... codes/httprequest.s"
	@echo "... codes/httpresponse.o"
	@echo "... codes/httpresponse.i"
	@echo "... codes/httpresponse.s"
	@echo "... codes/log.o"
	@echo "... codes/log.i"
	@echo "... codes/log.s"
	@echo "... codes/sqlconnpoll.o"
	@echo "... codes/sqlconnpoll.i"
	@echo "... codes/sqlconnpoll.s"
	@echo "... codes/webserver.o"
	@echo "... codes/webserver.i"
	@echo "... codes/webserver.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

